spring:
  main:
    sources: com.maggie.schedule.ScheduleProjectApplication
    allow-bean-definition-overriding: true   
   
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
info:
  app:
    name: "Member scheduling project"

management:
  endpoints:
    web:
      exposure:
        include: env,health,httptrace
        
logging:
  level:
    root: INFO
    com.maggie.schedule: DEBUG
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
---
spring:
  profiles: local
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

---
spring:
  profiles: dev